export const ACCENT_TOKENS = {
  indigo: {
    solidBg:        "bg-indigo-600 hover:bg-indigo-700",
    bgOnly:         "bg-indigo-600",
    headerGradient: "from-indigo-50/60",
    softBg:         "bg-indigo-50 dark:bg-indigo-500/10",
    softHoverBg:    "hover:bg-indigo-50/50 dark:hover:bg-indigo-500/10",
    text:           "text-indigo-600 dark:text-indigo-400",
    textStrong:     "text-indigo-700 dark:text-indigo-400",
    textHover:      "hover:text-indigo-600 dark:hover:text-indigo-400",
    icon:           "text-indigo-500",
    border:         "border-indigo-200 dark:border-indigo-500/30",
    ring:           "focus:ring-indigo-500",
    iconBg:         "bg-indigo-100 dark:bg-indigo-500/20",
    iconColor:      "text-indigo-600 dark:text-indigo-300",
  },
  blue: {
    solidBg:        "bg-blue-600 hover:bg-blue-700",
    bgOnly:         "bg-blue-600",
    headerGradient: "from-blue-50/60",
    softBg:         "bg-blue-50 dark:bg-blue-500/10",
    softHoverBg:    "hover:bg-blue-50/50 dark:hover:bg-blue-500/10",
    text:           "text-blue-600 dark:text-blue-400",
    textStrong:     "text-blue-700 dark:text-blue-400",
    textHover:      "hover:text-blue-600 dark:hover:text-blue-400",
    icon:           "text-blue-500",
    border:         "border-blue-200 dark:border-blue-500/30",
    ring:           "focus:ring-blue-500",
    iconBg:         "bg-blue-100 dark:bg-blue-500/20",
    iconColor:      "text-blue-600 dark:text-blue-300",
  },
  emerald: {
    solidBg:        "bg-emerald-600 hover:bg-emerald-700",
    bgOnly:         "bg-emerald-600",
    headerGradient: "from-emerald-50/60",
    softBg:         "bg-emerald-50 dark:bg-emerald-500/10",
    softHoverBg:    "hover:bg-emerald-50/50 dark:hover:bg-emerald-500/10",
    text:           "text-emerald-600 dark:text-emerald-400",
    textStrong:     "text-emerald-700 dark:text-emerald-400",
    textHover:      "hover:text-emerald-600 dark:hover:text-emerald-400",
    icon:           "text-emerald-500",
    border:         "border-emerald-200 dark:border-emerald-500/30",
    ring:           "focus:ring-emerald-500",
    iconBg:         "bg-emerald-100 dark:bg-emerald-500/20",
    iconColor:      "text-emerald-600 dark:text-emerald-300",
  },
  violet: {
    solidBg:        "bg-violet-600 hover:bg-violet-700",
    bgOnly:         "bg-violet-600",
    headerGradient: "from-violet-50/60",
    softBg:         "bg-violet-50 dark:bg-violet-500/10",
    softHoverBg:    "hover:bg-violet-50/50 dark:hover:bg-violet-500/10",
    text:           "text-violet-600 dark:text-violet-400",
    textStrong:     "text-violet-700 dark:text-violet-400",
    textHover:      "hover:text-violet-600 dark:hover:text-violet-400",
    icon:           "text-violet-500",
    border:         "border-violet-200 dark:border-violet-500/30",
    ring:           "focus:ring-violet-500",
    iconBg:         "bg-violet-100 dark:bg-violet-500/20",
    iconColor:      "text-violet-600 dark:text-violet-300",
  },
  rose: {
    solidBg:        "bg-rose-600 hover:bg-rose-700",
    bgOnly:         "bg-rose-600",
    headerGradient: "from-rose-50/60",
    softBg:         "bg-rose-50 dark:bg-rose-500/10",
    softHoverBg:    "hover:bg-rose-50/50 dark:hover:bg-rose-500/10",
    text:           "text-rose-600 dark:text-rose-400",
    textStrong:     "text-rose-700 dark:text-rose-400",
    textHover:      "hover:text-rose-600 dark:hover:text-rose-400",
    icon:           "text-rose-500",
    border:         "border-rose-200 dark:border-rose-500/30",
    ring:           "focus:ring-rose-500",
    iconBg:         "bg-rose-100 dark:bg-rose-500/20",
    iconColor:      "text-rose-600 dark:text-rose-300",
  },
};

export const ACCENT_HEX = {
  indigo:  { base: "#6366f1", soft: "#818cf8" },
  blue:    { base: "#3b82f6", soft: "#60a5fa" },
  emerald: { base: "#10b981", soft: "#34d399" },
  violet:  { base: "#8b5cf6", soft: "#a78bfa" },
  rose:    { base: "#f43f5e", soft: "#fb7185" },
};


export const DENSITY_TOKENS = {
  compact: {
    item:           "p-2",
    itemSm:         "px-2 py-1",
    itemXs:         "px-1.5 py-0.5",
    cellPadding:    "py-1.5 px-3",
    headerPadding:  "px-4 py-2.5",
    gap:            "gap-1",
    gapSm:          "gap-0.5",
    gapXs:          "gap-px",
    sectionMb:      "mb-3",
    sectionGap:     "gap-3",
    sectionPt:      "pt-3",
    textSize:       "text-[12.5px]",
    textSizeSm:     "text-[11px]",
    textSizeLg:     "text-[13px]",
    textSizeXs:     "text-[9px]",
    lineHeight:     "leading-snug",
    borderRadius:   "rounded-md",
    borderColor:    "border-gray-300 dark:border-gray-600",
    shadow:         "shadow-none",
    avatarSize:     "w-4 h-4",
    avatarSizeSm:   "w-4 h-4",
    avatarText:     "text-[8px]",
    iconSize:       14,
    iconSizeSm:     12,
  },
  normal: {
    item:           "p-3",
    itemSm:         "px-3 py-2",
    itemXs:         "px-2 py-1",
    cellPadding:    "py-3 px-4",
    headerPadding:  "px-6 py-4",
    gap:            "gap-3",
    gapSm:          "gap-2",
    gapXs:          "gap-1",
    sectionMb:      "mb-5",
    sectionGap:     "gap-5",
    sectionPt:      "pt-5",
    textSize:       "text-[13px]",
    textSizeSm:     "text-[11.5px]",
    textSizeLg:     "text-[14px]",
    textSizeXs:     "text-[10px]",
    lineHeight:     "leading-relaxed",
    borderRadius:   "rounded-xl",
    borderColor:    "border-gray-200/60 dark:border-gray-700/60",
    shadow:         "shadow-sm",
    avatarSize:     "w-5 h-5",
    avatarSizeSm:   "w-5 h-5",
    avatarText:     "text-[9px]",
    iconSize:       16,
    iconSizeSm:     14,
  },
  comfortable: {
    item:           "p-4",
    itemSm:         "px-4 py-3",
    itemXs:         "px-3 py-2",
    cellPadding:    "py-4 px-5",
    headerPadding:  "px-6 py-4",
    gap:            "gap-4",
    gapSm:          "gap-3",
    gapXs:          "gap-2",
    sectionMb:      "mb-6",
    sectionGap:     "gap-6",
    sectionPt:      "pt-6",
    textSize:       "text-[14px]",
    textSizeSm:     "text-[12.5px]",
    textSizeLg:     "text-[15px]",
    textSizeXs:     "text-[11px]",
    lineHeight:     "leading-relaxed",
    borderRadius:   "rounded-2xl",
    borderColor:    "border-gray-200 dark:border-gray-700",
    shadow:         "shadow-md",
    avatarSize:     "w-7 h-7",
    avatarSizeSm:   "w-6 h-6",
    avatarText:     "text-[10px]",
    iconSize:       18,
    iconSizeSm:     16,
  },
};

export const getAccent = (accent = "indigo") =>
  ACCENT_TOKENS[accent] ?? ACCENT_TOKENS.indigo;

export const getAccentHex = (accent = "indigo") =>
  ACCENT_HEX[accent] ?? ACCENT_HEX.indigo;

export const getDensity = (d = "comfortable") =>
  DENSITY_TOKENS[d] ?? DENSITY_TOKENS.comfortable;